spring.application.name=portalku
spring.profiles.active=dev

app.nama=Portal Jurnal PSDKU Lumajang
app.versi=0.1.0
app.maks-item=50

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method